Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Installing prometheus
  config.vm.provision "shell", privileged: false, inline: "wget -t 10 -O /home/vagrant/prometheus.tar.gz --retry-connrefused -nv https://github.com/prometheus/prometheus/releases/download/v1.5.0/prometheus-1.5.0.linux-amd64.tar.gz"
  config.vm.provision "shell", privileged: false, inline: "wget -t 10 -O /home/vagrant/pushgateway.tar.gz --retry-connrefused -nv https://github.com/prometheus/pushgateway/releases/download/v0.3.1/pushgateway-0.3.1.linux-amd64.tar.gz"
  config.vm.provision "shell", privileged: false,  inline: "tar -C /home/vagrant -xvzf /home/vagrant/prometheus.tar.gz"
  config.vm.provision "shell", privileged: false,  inline: "tar -C /home/vagrant -xvzf /home/vagrant/pushgateway.tar.gz"
  config.vm.provision "shell", privileged: false,  inline: "rm /home/vagrant/prometheus.tar.gz"
  config.vm.provision "shell", privileged: false,  inline: "rm /home/vagrant/pushgateway.tar.gz"
  config.vm.provision "shell", privileged: false,  inline: "mv /home/vagrant/prometheus-* /home/vagrant/prometheus"
  config.vm.provision "shell", privileged: false,  inline: "mv /home/vagrant/pushgateway-* /home/vagrant/pushgateway"
  config.vm.provision "shell", privileged: false,  inline: "rm -rf /home/vagrant/prometheus-*"
  config.vm.provision "shell", privileged: false,  inline: "rm -rf /home/vagrant/pushgateway-*"
  config.vm.provision "shell", privileged: false,  inline: "rm /home/vagrant/prometheus/prometheus.yml"
  config.vm.provision "shell", inline: "cp /vagrant/files/prometheus.yml /home/vagrant/prometheus/prometheus.yml"
  config.vm.provision "shell", inline: "cp /vagrant/files/prometheus.service /etc/systemd/system/"
  config.vm.provision "shell", inline: "cp /vagrant/files/pushgateway.service /etc/systemd/system/"
  config.vm.provision "shell", inline: "chown root:root /etc/systemd/system/prometheus.service"
  config.vm.provision "shell", inline: "chown root:root /etc/systemd/system/pushgateway.service"
  config.vm.provision "shell", inline: "systemctl daemon-reload" 
end
